services:
  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_container
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./:/code # for local dev: binded mount to reload changes to docker: host currentdir to docker /app dir

volumes:
  postgres_data:
