services:
  db:
    image: postgres:15
    container_name: postgres_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    env_file:
      - .env.aws
  db-init:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: db_init_container
    depends_on:
      - db
    env_file:
      - .env.aws
    command: [ "python", "-u", "-m", "app.db_init" ]
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi_container
    depends_on:
      db-init:
        condition: service_completed_successfully
    ports:
      - "8000:8000"
    env_file:
      - .env.aws
    volumes:
      - ./:/code # for local dev: binded mount to reload changes to docker: host currentdir to docker /app dir
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    container_name: worker_container
    depends_on:
      db-init:
        condition: service_completed_successfully
    volumes:
      - /tmp:/tmp
    env_file:
      - .env.aws
volumes:
  postgres_data:
